# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScenarioDbRecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ScenarioDbRecord.proto',
  package='',
  serialized_pb=_b('\n\x16ScenarioDbRecord.proto\"f\n\rGameSetupRule\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x1c\n\trule_type\x18\x02 \x02(\x0e\x32\t.RuleType\x12\r\n\x05\x64\x61ta1\x18\x03 \x02(\x03\x12\r\n\x05\x64\x61ta2\x18\x04 \x02(\x03\x12\r\n\x05\x64\x61ta3\x18\x05 \x02(\x03\"5\n\x14LocalizedStringValue\x12\x0e\n\x06locale\x18\x01 \x02(\x05\x12\r\n\x05value\x18\x02 \x02(\t\"z\n\x0fLocalizedString\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x18\n\x10\x64\x65precated_value\x18\x02 \x01(\t\x12\x19\n\x11\x64\x65precated_locale\x18\x03 \x01(\x05\x12%\n\x06values\x18\x04 \x03(\x0b\x32\x15.LocalizedStringValue\"%\n\x07Vector2\x12\x0c\n\x01x\x18\x01 \x02(\x02:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x02:\x01\x30\"\xc9\x03\n\x10ScenarioDbRecord\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\tnote_desc\x18\x02 \x01(\t\x12\x13\n\x0bnum_players\x18\x03 \x02(\x05\x12\x1c\n\x14player1_hero_card_id\x18\x04 \x02(\x03\x12\x1c\n\x14player2_hero_card_id\x18\x05 \x02(\x03\x12\x11\n\tis_expert\x18\x06 \x02(\x08\x12\x14\n\x0c\x61\x64venture_id\x18\x07 \x02(\x05\x12\x19\n\x11\x61\x64venture_mode_id\x18\x08 \x01(\x05\x12\x0f\n\x07wing_id\x18\t \x02(\x05\x12\x12\n\nsort_order\x18\n \x02(\x05\x12#\n\x1b\x63lient_player2_hero_card_id\x18\x0b \x01(\x03\x12\x1c\n\x14tavern_brawl_texture\x18\x0c \x01(\t\x12\"\n\x1atavern_brawl_texture_phone\x18\r \x01(\t\x12\x33\n!tavern_brawl_texture_phone_offset\x18\x0e \x01(\x0b\x32\x08.Vector2\x12!\n\x07strings\x18\x64 \x03(\x0b\x32\x10.LocalizedString\x12\x1d\n\x05rules\x18\x65 \x03(\x0b\x32\x0e.GameSetupRule*E\n\x08RuleType\x12\r\n\tRULE_NONE\x10\x00\x12\x14\n\x10RULE_CHOOSE_HERO\x10\x01\x12\x14\n\x10RULE_CHOOSE_DECK\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RULETYPE = _descriptor.EnumDescriptor(
  name='RuleType',
  full_name='RuleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RULE_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RULE_CHOOSE_HERO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RULE_CHOOSE_DECK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=808,
  serialized_end=877,
)
_sym_db.RegisterEnumDescriptor(_RULETYPE)

RuleType = enum_type_wrapper.EnumTypeWrapper(_RULETYPE)
RULE_NONE = 0
RULE_CHOOSE_HERO = 1
RULE_CHOOSE_DECK = 2



_GAMESETUPRULE = _descriptor.Descriptor(
  name='GameSetupRule',
  full_name='GameSetupRule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GameSetupRule.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rule_type', full_name='GameSetupRule.rule_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data1', full_name='GameSetupRule.data1', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data2', full_name='GameSetupRule.data2', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data3', full_name='GameSetupRule.data3', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=128,
)


_LOCALIZEDSTRINGVALUE = _descriptor.Descriptor(
  name='LocalizedStringValue',
  full_name='LocalizedStringValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locale', full_name='LocalizedStringValue.locale', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='LocalizedStringValue.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=183,
)


_LOCALIZEDSTRING = _descriptor.Descriptor(
  name='LocalizedString',
  full_name='LocalizedString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='LocalizedString.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deprecated_value', full_name='LocalizedString.deprecated_value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deprecated_locale', full_name='LocalizedString.deprecated_locale', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='LocalizedString.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=307,
)


_VECTOR2 = _descriptor.Descriptor(
  name='Vector2',
  full_name='Vector2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2.x', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2.y', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=346,
)


_SCENARIODBRECORD = _descriptor.Descriptor(
  name='ScenarioDbRecord',
  full_name='ScenarioDbRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ScenarioDbRecord.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='note_desc', full_name='ScenarioDbRecord.note_desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_players', full_name='ScenarioDbRecord.num_players', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player1_hero_card_id', full_name='ScenarioDbRecord.player1_hero_card_id', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player2_hero_card_id', full_name='ScenarioDbRecord.player2_hero_card_id', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_expert', full_name='ScenarioDbRecord.is_expert', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adventure_id', full_name='ScenarioDbRecord.adventure_id', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adventure_mode_id', full_name='ScenarioDbRecord.adventure_mode_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wing_id', full_name='ScenarioDbRecord.wing_id', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sort_order', full_name='ScenarioDbRecord.sort_order', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_player2_hero_card_id', full_name='ScenarioDbRecord.client_player2_hero_card_id', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tavern_brawl_texture', full_name='ScenarioDbRecord.tavern_brawl_texture', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tavern_brawl_texture_phone', full_name='ScenarioDbRecord.tavern_brawl_texture_phone', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tavern_brawl_texture_phone_offset', full_name='ScenarioDbRecord.tavern_brawl_texture_phone_offset', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strings', full_name='ScenarioDbRecord.strings', index=14,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rules', full_name='ScenarioDbRecord.rules', index=15,
      number=101, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=806,
)

_GAMESETUPRULE.fields_by_name['rule_type'].enum_type = _RULETYPE
_LOCALIZEDSTRING.fields_by_name['values'].message_type = _LOCALIZEDSTRINGVALUE
_SCENARIODBRECORD.fields_by_name['tavern_brawl_texture_phone_offset'].message_type = _VECTOR2
_SCENARIODBRECORD.fields_by_name['strings'].message_type = _LOCALIZEDSTRING
_SCENARIODBRECORD.fields_by_name['rules'].message_type = _GAMESETUPRULE
DESCRIPTOR.message_types_by_name['GameSetupRule'] = _GAMESETUPRULE
DESCRIPTOR.message_types_by_name['LocalizedStringValue'] = _LOCALIZEDSTRINGVALUE
DESCRIPTOR.message_types_by_name['LocalizedString'] = _LOCALIZEDSTRING
DESCRIPTOR.message_types_by_name['Vector2'] = _VECTOR2
DESCRIPTOR.message_types_by_name['ScenarioDbRecord'] = _SCENARIODBRECORD
DESCRIPTOR.enum_types_by_name['RuleType'] = _RULETYPE

GameSetupRule = _reflection.GeneratedProtocolMessageType('GameSetupRule', (_message.Message,), dict(
  DESCRIPTOR = _GAMESETUPRULE,
  __module__ = 'ScenarioDbRecord_pb2'
  # @@protoc_insertion_point(class_scope:GameSetupRule)
  ))
_sym_db.RegisterMessage(GameSetupRule)

LocalizedStringValue = _reflection.GeneratedProtocolMessageType('LocalizedStringValue', (_message.Message,), dict(
  DESCRIPTOR = _LOCALIZEDSTRINGVALUE,
  __module__ = 'ScenarioDbRecord_pb2'
  # @@protoc_insertion_point(class_scope:LocalizedStringValue)
  ))
_sym_db.RegisterMessage(LocalizedStringValue)

LocalizedString = _reflection.GeneratedProtocolMessageType('LocalizedString', (_message.Message,), dict(
  DESCRIPTOR = _LOCALIZEDSTRING,
  __module__ = 'ScenarioDbRecord_pb2'
  # @@protoc_insertion_point(class_scope:LocalizedString)
  ))
_sym_db.RegisterMessage(LocalizedString)

Vector2 = _reflection.GeneratedProtocolMessageType('Vector2', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR2,
  __module__ = 'ScenarioDbRecord_pb2'
  # @@protoc_insertion_point(class_scope:Vector2)
  ))
_sym_db.RegisterMessage(Vector2)

ScenarioDbRecord = _reflection.GeneratedProtocolMessageType('ScenarioDbRecord', (_message.Message,), dict(
  DESCRIPTOR = _SCENARIODBRECORD,
  __module__ = 'ScenarioDbRecord_pb2'
  # @@protoc_insertion_point(class_scope:ScenarioDbRecord)
  ))
_sym_db.RegisterMessage(ScenarioDbRecord)


# @@protoc_insertion_point(module_scope)
